---
title: "Data Cleaning and Exploration"
output: html_document
---
```{r}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(tidyverse)         # for reading in data, graphing, and cleaning
library(tidymodels)        # for modeling ... tidily
library(usemodels)         # for suggesting step_XXX() functions
library(glmnet)            # for regularized regression, including LASSO
library(naniar)            # for examining missing values (NAs)
library(lubridate)         # for date manipulation
library(moderndive)        # for King County housing data
library(vip)               # for variable importance plots
library(rmarkdown)         # for paged tables
library(readr)
library(fastDummies)
library(kableExtra)
theme_set(theme_minimal()) # my favorite ggplot2 theme :)
```


```{r}
# read in data
fullFile <-read.csv("fullFile.csv")
macro<-read.csv("clean_macro - Sheet1.csv")
```

```{r}
# merge accounting data with macro data
final_data <- fullFile %>% 
  left_join(macro, by = "YEAR") %>% 
  # calculate earning next year and return
  group_by(COMPANY) %>% 
  mutate(Earnings_next_year = lead(EARNINGS, n = 1, order_by = YEAR),
         PROFIT = (Sell - PRICE) / PRICE * 100) %>% 
  # change duplicated names
  rename(Name=Name.y,Sector = Sector.y) %>% 
  # create dummy variables
  dummy_cols(select_columns = "Sector") %>% 
  mutate_at(vars(matches("Sector")),~as.factor(.)) %>% 
  # convert Macro factors from characters to numeric
  mutate(across(c("CPALTT01USM657N_PC1","GDP","GDP_PC1","T10Y2Y","M1SL_PC1","M1SL"),
                as.numeric)) %>% 
  # delete less important factors -> Exchange can possibily be deleted
  select(-Name.x,-Sector.x,-observation_date,-Name) %>% 
  mutate(across(c(!where(is.numeric),-"COMPANY"),as.factor)) %>% 
  filter(YEAR<2021)
#colnames(final_data)  
```

```{r}
final_data %>% 
  select(where(is.numeric)) %>% 
  summary() %>% 
  kbl()

final_data %>% 
  select(!where(is.numeric)) %>% 
  summary() %>% 
  kbl()
```

```{r}

  final_data %>% 
  select(where(is.numeric)) %>% 
  select(0:12) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(vars(variable), 
             scales = "free",
             nrow = 3,
             ncol=4)

 final_data %>% 
  select(where(is.numeric)) %>% 
  select(13:24) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(vars(variable), 
             scales = "free",
             nrow = 3)
 
 final_data %>% 
  select(where(is.numeric)) %>% 
  select(25:36) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(vars(variable), 
             scales = "free",
             nrow = 3,
             ncol=4)

  final_data %>% 
  select(where(is.numeric)) %>% 
  select(37:41) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(vars(variable), 
             scales = "free",
             nrow = 3,
             ncol=4)



```
```{r}
final_data %>% 
  select(where(is.factor)) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value") %>% 
  ggplot(aes(x = value)) +
  geom_bar() +
  facet_wrap(vars(variable), 
             scales = "free", 
             nrow = 4)
```

Question after data exploration:   
1. There are many rows in SellingAndMrketing Expenses that are -1. Is that a mistake?   
2. Our predictors and outcomes are very right skewed. Should we do log transformation or generating "fake data" before building the model?   
3. Are there potential problems with interacting industry dummies with Macro data?   