---
title: "RandomForest_FinalVersion"
author: "Sivhuo Prak (Siv)"
date: "12/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

## Load the Data
```{r}
library(tidyverse)         # for reading in data, graphing, and cleaning
library(tidymodels)        # for modeling ... tidily
library(stacks)            # for stacking models
library(glmnet)            # for regularized regression, including LASSO
library(ranger)            # for random forest model
library(kknn)              # for knn model
library(naniar)            # for examining missing values (NAs)
library(lubridate)         # for date manipulation
library(moderndive)        # for King County housing data
library(vip)               # for variable importance plots
library(rmarkdown)         # for paged tables
library(usemodels)         # for suggesting step_XXX() functions
library(naniar)            # for examining missing values (NAs)
library(readr)
library(fastDummies)
library(kableExtra)
library(DALEX)             # moDel Agnostic Language for Exploration and eXplanation (for model interpretation)  
library(DALEXtra)
theme_set(theme_minimal()) # my favorite ggplot2 theme :)
```

## Data Processing
```{r}
finalDATASET <- read_csv("FINALDATASET.csv")

final_data <- finalDATASET %>% 
  dummy_cols(select_columns = "Sector") %>% 
  # mutate_at(vars(matches("Sector")),~as.factor(.)) %>% 
  # convert Macro factors from characters to numeric
  mutate(across(c("CPALTT01USM657N_PC1","GDP","GDP_PC1","T10Y2Y","M1SL_PC1","M1SL"),
                as.numeric)) %>% 
  mutate(across(c(DEBTS,INVESTMENTS,CASH,VOLUME,EARNINGS,COGS,SALES,RECEIVABLE,INVENTORY),~replace(.,.==0,NA))) %>% 
  # delete less important factors -> Exchange can possibily be deleted
  #select(-Name.x,-Sector.x,-observation_date,-Name) %>% 
  mutate(across(c(!where(is.numeric),-"COMPANY"),as.factor)) 
```

```{r}
final_data <- final_data %>% 
  select(-Earnings_next_year,-PRICE,-Sell)
```

```{r}
final_data$EARNINGS[is.na(final_data$EARNINGS)]<-median(final_data$EARNINGS,na.rm=TRUE)
final_data$INVESTMENTS[is.na(final_data$INVESTMENTS)]<-median(final_data$INVESTMENTS,na.rm=TRUE)
final_data$DEBTS[is.na(final_data$DEBTS)]<-median(final_data$DEBTS,na.rm=TRUE)
final_data$COGS[is.na(final_data$COGS)]<-median(final_data$COGS,na.rm=TRUE)
final_data$SALES[is.na(final_data$SALES)]<-median(final_data$SALES,na.rm=TRUE)
final_data$CASH[is.na(final_data$CASH)]<-median(final_data$CASH,na.rm=TRUE)
final_data$RECEIVABLE[is.na(final_data$RECEIVABLE)]<-median(final_data$RECEIVABLE,na.rm=TRUE)
```

```{r}
final_data <- final_data %>% 
  drop_na()
```

```{r}
set.seed(327) #for reproducibility

# Randomly assigns 75% of the data to training.
data_split <- initial_split(final_data, 
                             prop = .75)
data_training <- training(data_split)
data_testing <- testing(data_split)
```

## Building Recipe
```{r}
ranger_recipe <-
  recipe(PROFIT ~ ., #short-cut, . = all other vars
                       data = data_training) %>%
  step_filter(YEAR<2021) %>% 
  # remove the unwanted variables
  step_rm(YEAR,COMPANY,PRICE,Sell,Name,GDP,M1SL,Sector) %>% 
  # add PE 
  step_mutate(PE = `MARKET CAP`/EARNINGS)
```

## Building the Lasso model
```{r}
ranger_spec <- 
  rand_forest(mtry = 10, 
              min_n = 10, 
              trees = 200) %>% 
  set_mode("regression") %>% 
  set_engine("ranger")
```

```{r}
ranger_workflow <- 
  workflow() %>% 
  add_recipe(ranger_recipe) %>% 
  add_model(ranger_spec)
```

```{r}
ranger_fit <- ranger_workflow %>% 
  fit(data_training)

ranger_fit
```

## Random Forest results
```{r}
# OOB error (MSE) ... 
ranger_fit$fit$fit$fit$prediction.error
#OOB RMSE
sqrt(ranger_fit$fit$fit$fit$prediction.error)
# R squared
ranger_fit$fit$fit$fit$r.squared
```

## Model Evaluation
### Prediciton precision (Traning data)
```{r}
set.seed(1211) # for reproducibility
data_cv <- vfold_cv(data_training, v = 5)

metric <- metric_set(rmse)
ctrl_res <- control_stack_resamples()

ranger_cv <- ranger_workflow %>% 
  fit_resamples(data_cv, 
                metrics = metric,
                control = ctrl_res)

# Evaluation metrics averaged over all folds:
collect_metrics(ranger_cv)
```

```{r}
ranger_prediction <- predict(
  ranger_fit,
  new_data = data_training)

ranger_training_pred<-data_training %>% 
  mutate(.pred = ranger_prediction$.pred)
  
  
ranger_training_pred %>%
  ggplot(aes(x = PROFIT,
             y = .pred)) +
  geom_point(alpha = .5,
             size = .5) +
  geom_smooth(se = FALSE) +
  geom_abline(slope = 1,
              intercept = 0,
              color = "darkred") +
  geom_text(aes(label = Name),data = ranger_training_pred %>% filter(PROFIT>200) )+
  labs(x = "Actual Return",
       y = "Predicted Return")

```
### Prediciton precision (Testing data)
```{r}
set.seed(1211) # for reproducibility
data_cv <- vfold_cv(data_testing, v = 5)

metric <- metric_set(rmse)
ctrl_res <- control_stack_resamples()

ranger_cv <- ranger_workflow %>% 
  fit_resamples(data_cv, 
                metrics = metric,
                control = ctrl_res)

# Evaluation metrics averaged over all folds:
collect_metrics(ranger_cv)
```

```{r}
ranger_test_prediction <- predict(
  ranger_fit,
  new_data = data_testing)

ranger_test_pred<-data_testing %>% 
  mutate(.pred = ranger_test_prediction$.pred)
  
  
ranger_test_pred %>%
  ggplot(aes(x = PROFIT,
             y = .pred)) +
  geom_point(alpha = .5,
             size = .5) +
  geom_smooth(se = FALSE) +
  geom_abline(slope = 1,
              intercept = 0,
              color = "darkred") +
  geom_text(aes(label = Name),data = ranger_test_pred %>% filter(PROFIT>200) )+
  labs(x = "Actual Return",
       y = "Predicted Return")

```

## Interpretable Machine Learning 
```{r}
rf_explain <- 
  explain_tidymodels(
    model = ranger_fit,
    data = data_training %>% select(-PROFIT), 
    y = data_training %>%  pull(PROFIT),
    label = "rf"
  )
rf_mod_perf <-  model_performance(rf_explain)

hist_plot <- 
  plot(rf_mod_perf, 
       geom = "histogram")
box_plot <-
  plot(rf_mod_perf, 
       geom = "boxplot")

hist_plot
box_plot
```
```{r}
set.seed(10) #since we are sampling & permuting, we set a seed so we can replicate the results
rf_var_imp <- 
  model_parts(
    rf_explain
    )
plot(rf_var_imp, show_boxplots = TRUE)
```





